---
# requirements install
#- name: Install Roles from Galaxy
#  hosts: all
#  connection: local
#  tasks:
#    - name: installing required ansible-galaxy roles
#      command: "ansible-galaxy install --ignore-errors -r requirements.yml"

# Let's rock on ALM
- name: yum update packages
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes

  roles:
    - linuxupdate.packages

- name: yum update packages
  hosts: sonar_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes

  roles:
    - linuxupdate.packages

- name: yum update packages
  hosts: app_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes

  roles:
    - linuxupdate.packages

- name: Deploy Jenkins CI
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.jenkins
    - geerlingguy.git
    - tecris.maven
    - geerlingguy.ansible

- name: jenkins copy-key from master
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: copy
      copy:
       src: /root/Ansible-Automation/aws-private.pem
       dest: /root/aws-private.pem
       owner: jenkins
       group: jenkins
       mode: 0700

- name: jenkins pipeline configuration
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: Creates directory
      file:
       path: /var/lib/jenkins/jobs/soccer/
       state: directory
       owner: jenkins
       group: jenkins
       mode: 0700
    - name: copy
      copy:
       src: /root/Ansible-Automation/vagrant-alm/ansible/jenkins/config.xml
       dest: /var/lib/jenkins/jobs/soccer/config.xml
       owner: jenkins
       group: jenkins
       mode: 0700
 


- name: jenkins pipeline Credentials configuration
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: copy
      copy:
       src: credentials.xml
       dest: /var/lib/jenkins/credentials.xml
       owner: jenkins
       group: jenkins
       mode: 0700

- name: jenkins pipeline sonar global configuration
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: copy
      copy:
       src: hudson.plugins.sonar.SonarGlobalConfiguration.xml
       dest: /var/lib/jenkins/hudson.plugins.sonar.SonarGlobalConfiguration.xml
       owner: jenkins
       group: jenkins
       mode: 0700

- name: jenkins pipeline maven configuration
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: copy
      copy:
       src: hudson.tasks.Maven.xml
       dest: /var/lib/jenkins/hudson.tasks.Maven.xml
       owner: jenkins
       group: jenkins
       mode: 0700

- name: jenkins pipeline qualitygates configuration
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: copy
      copy:
       src: org.quality.gates.jenkins.plugin.GlobalConfig.xml
       dest: /var/lib/jenkins/org.quality.gates.jenkins.plugin.GlobalConfig.xml
       owner: jenkins
       group: jenkins
       mode: 0700

- name: jenkins pipeline nexus configuration
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: copy
      copy:
       src: org.sonatype.nexus.ci.config.GlobalNexusConfiguration.xml
       dest: /var/lib/jenkins/org.sonatype.nexus.ci.config.GlobalNexusConfiguration.xml
       owner: jenkins
       group: jenkins
       mode: 0700

- name: jenkins pipeline sonarquality configuration
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: copy
      copy:
       src: quality.gates.jenkins.plugin.GlobalConfig.xml
       dest: /var/lib/jenkins/quality.gates.jenkins.plugin.GlobalConfig.xml
       owner: jenkins
       group: jenkins
       mode: 0700

- name: jenkins pipeline Credentials configuration
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: copy
      copy:
       src: config.xml
       dest: /var/lib/jenkins/config.xml
       owner: jenkins
       group: jenkins
       mode: 0700

- name: jenkins pipeline plugin configuration
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: Adding Plugin
      jenkins_plugin:
          name: "{{ item }}"
          url_username: admin
          url_password: admin123
          url: http://localhost:8080
      with_items:
           - quality-gates
           - nexus-jenkins-plugin
           - sonar-quality-gates
      tags: ['skip_ansible_lint']
      register: plugin_result
      until: plugin_result is success
      retries: 3
      delay: 2

- name: jenkins restart server
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: Restart Jenkins to make the plugin data available
      service: name=jenkins state=restarted
    - name: Wait for Jenkins to restart
      wait_for:
          host=localhost
          port=8080
          delay=20
          timeout=300

- name: jenkins copy appserver host
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - lineinfile:
        src: /root/Ansible-Automation/vagrant-alm/ansible/jenapphost 
        dest: /etc/ansible/hosts
        regexp: '^[webserver]'
        insertafter: '^#[webservers]'
        line: '[app_server]'
               
- name: jenkins copy appserver host
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - lineinfile:
        src: /root/Ansible-Automation/vagrant-alm/ansible/jenapphost
        dest: /etc/ansible/hosts
        regexp: '^[webserver]'
        insertafter: '^#[webservers]'
        line: '10.0.1.21 ansible_ssh_user=centos ansible_ssh_private_key_file=/home/centos/aws-private.pem ansible_ssh_pass=rohith'


- name: jenkins server sshd permissions
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: uncomment PermitRootLogin 
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#PermitRootLogin yes'
        replace: 'PermitRootLogin  yes'
    - name: uncomment PasswordAuthentication 
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#PasswordAuthentication yes'
        replace: 'PasswordAuthentication yes'
    - name: Restart sshd
      service: name=sshd state=restarted

- name: jenkins server host_key_checking
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: uncomment host_key_checking 
      replace:
        path: /etc/ansible/ansible.cfg
        regexp: '#host_key_checking = False'
        replace: 'host_key_checking = False'

#- name: set password for centos user
#  hosts: jenkins_server
#  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
#  become: yes
#  tasks:
#    - name: set centos password
#      user: name=centos update_password=always password=rohith

- name: Deploy Nexus Server
  hosts: nexus_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes

  roles:
    - geerlingguy.java
    - dockpack.nexus

- name: Deploy Sonar Server
  hosts: sonar_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes

  roles:
    - wtanaka.unzip
    - zanini.sonar

#- name: Deploy rundeck Server
#  hosts: app_server
#  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
#  become: yes

#  roles:
#    - robertdebock.bootstrap
#    - robertdebock.java
#    - robertdebock.service
#    - robertdebock.rundeck 

- name: application server sshd permissions
  hosts: app_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: uncomment PermitRootLogin 
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#PermitRootLogin yes'
        replace: 'PermitRootLogin  yes'
    - name: uncomment PasswordAuthentication 
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#PasswordAuthentication yes'
        replace: 'PasswordAuthentication yes'
    - name: Restart sshd
      service: name=sshd state=restarted

#- name: set password for centos user
#  hosts: jenkins_server
#  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
#  become: yes
#  tasks:
#    - name: set centos password
#      user: name=centos update_password=always password=rohith   

- name: On Premises CentOS
  hosts: app_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes

  roles:
    - jenkins-keys-config
      
    
