---
- name: jenkins copy-key from master
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: copy
      copy:
       src: /root/Ansible-Automation/rohith_tasks/aws-private.pem
       dest: /root/aws-private.pem
       owner: jenkins
       group: jenkins
       mode: 0644

- name: create new user
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:

  roles:
    - lnovara.deploy-user

- name: set password for existing user
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: create password
      user: name=deploy update_password=always password=$6$DZ8HJeMI$pbz5Lb8eVAs5Q/GJhCnml6hdDELlyyb37itrYbIYtlsJQqM9xKyY/bPEkZnmC9l5iBOa7Pix/YRaxCiLGF9NK1



- name: jenkins server host_key_checking
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: uncomment host_key_checking
      replace:
        path: /etc/ansible/ansible.cfg
        regexp: '#host_key_checking = False'
        replace: 'host_key_checking = False'

- name: jenkins server sshd permissions
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: uncomment PermitRootLogin
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#PermitRootLogin yes'
        replace: 'PermitRootLogin  yes'
    - name: uncomment PasswordAuthentication
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#PasswordAuthentication yes'
        replace: 'PasswordAuthentication yes'
    - name: Restart sshd
      service: name=sshd state=restarted

- name: jenkins copy appserver host
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - lineinfile:
        src: /root/Ansible-Automation/vagrant-alm/ansible/jenapphost
        dest: /etc/ansible/hosts
        regexp: '^[webserver]'
        insertafter: '^#[webservers]'
        line: '[app_server]'

- name: jenkins copy appserver host
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - lineinfile:
        src: /root/Ansible-Automation/vagrant-alm/ansible/jenapphost
        dest: /etc/ansible/hosts
        regexp: '^[webserver]'
        insertafter: '^#[webservers]'
        line: '10.0.1.21 ansible_ssh_user=deploy ansible_ssh_private_key_file=/home/centos/aws-private.pem ansible_ssh_pass=rohith'
