---
- name: jenkins pipeline configuration
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: Creates directory
      file:
       path: /var/lib/jenkins/jobs/soccer/
       state: directory
       owner: jenkins
       group: jenkins
       mode: 0700
    - name: copy
      copy:
       src: /root/Ansible-Automation/vagrant-alm/ansible/jenkinsconfig/config.xml
       dest: /var/lib/jenkins/jobs/soccer/config.xml
       owner: jenkins
       group: jenkins
       mode: 0644


- name: jenkins pipeline configuration
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: Creates directory
      file:
       path: /var/lib/jenkins/jobs/petclinic/
       state: directory
       owner: jenkins
       group: jenkins
       mode: 0700
    - name: copy
      copy:
       src: config.xml
       dest: /var/lib/jenkins/jobs/petclinic/config.xml
       owner: jenkins
       group: jenkins
       mode: 0700

- name: jenkins pipeline Credentials configuration
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: copy
      copy:
       src: /root/Ansible-Automation/vagrant-alm/ansible/jenkinsconfig/credentials.xml
       dest: /var/lib/jenkins/credentials.xml
       owner: jenkins
       group: jenkins
       mode: 0644

- name: jenkins secrets hudson secret configuration
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: Creates directory
      file:
       path: /var/lib/jenkins/secrets/
       state: directory
       owner: jenkins
       group: jenkins
       mode: 0700
    - name: copy
      copy:
       src: /root/Ansible-Automation/vagrant-alm/ansible/jenkinsconfig/hudson.util.Secret
       dest: /var/lib/jenkins/secrets/hudson.util.Secret
       owner: jenkins
       group: jenkins
       mode: 0644

- name: jenkins secrets-master.key configuration
  hosts: jenkins_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
    - name: copy
      copy:
       src: /root/Ansible-Automation/vagrant-alm/ansible/jenkinsconfig/master.key
       dest: /var/lib/jenkins/secrets/master.key
       owner: jenkins
       group: jenkins
       mode: 0644
