# This is for reference only dont run this , everthing is there under roles directory
- src: geerlingguy.java

- src: geerlingguy.jenkins

- src: geerlingguy.postgresql

- src: geerlingguy.sonar

- src: wtanaka.unzip

- src: savoirfairelinux.nexus3-oss

- src: dockpack.nexus

- src: geerlingguy.git

- src: tecris.maven

- src: geerlingguy.repo-epel

- src: geerlingguy.ansible

