- name: Deploy rundeck Server
  hosts: app_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes

  roles:
    - robertdebock.bootstrap
    - robertdebock.java
    - robertdebock.service
    - robertdebock.rundeck
